GitLoveApp/Models/Devotional.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GitLoveApp.Models
{
    public class Devotional
    {
        [Key]
        public int DevotionalId { get; set; }
        [Required(ErrorMessage = "Your Post is required")]
        [DataType(DataType.MultilineText)]
        public string DevotionalPost { get; set; }
        public int Rating { get; set; }
        public DateTime PostDate { get; set; }

        [ForeignKey("CreatedByUser")]
        public virtual string CreatedById { get; set; }
        public ApplicationUser CreatedByUser { get; set; }

    }
}

GitLoveApp/Controllers/DevotionalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GitLoveApp.Models;
using Microsoft.AspNet.Identity;
using System.Net.Mail;

namespace GitLoveApp.Controllers
{
    public class DevotionalController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Devotional
        public ActionResult Index()
        {
            var devotionals = db.Devotionals.Include(d => d.CreatedByUser);
            return View(devotionals.ToList());
        }

        // GET: Devotional/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Devotional devotional = db.Devotionals.Find(id);
            if (devotional == null)
            {
                return HttpNotFound();
            }
            return View(devotional);
        }

        // GET: Devotional/Create
        [Authorize]
        public ActionResult Create()
        {
            //ViewBag.CreatedById = new SelectList(db.ApplicationUsers, "Id", "FirstName");
            return View();
        }

        // POST: Devotional/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DevotionalPost")] Devotional devotional)
        {
            if (ModelState.IsValid)
            {
                devotional.Rating = 0;
                devotional.CreatedById = User.Identity.GetUserId();
                devotional.PostDate = DateTime.Now;

                db.Devotionals.Add(devotional);
                db.SaveChanges();

                MailMessage mail = new MailMessage();
                SmtpClient client = new SmtpClient();
                client.Port = 587;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.UseDefaultCredentials = false;
                client.Host = "smtp.mail.yahoo.com";
                client.EnableSsl = true;
                client.Credentials = new NetworkCredential("bill-vickers@att.net", "GavinLucas1");
                mail.To.Add(new MailAddress("bill-vickers@att.net"));
                mail.From = new MailAddress("househunter.realty@att.net");
                mail.Subject = "Something was posted";
                mail.Body = "You have received a post in GitLove.org.";
                client.Send(mail);

                return RedirectToAction("ThankYou");
            }

            //ViewBag.CreatedById = new SelectList(db.ApplicationUsers, "Id", "FirstName", devotional.CreatedById);
            return View(devotional);
        }

        // GET: Devotional/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Devotional devotional = db.Devotionals.Find(id);
            if (devotional == null)
            {
                return HttpNotFound();
            }
            //ViewBag.CreatedById = new SelectList(db.ApplicationUsers, "Id", "FirstName", devotional.CreatedById);
            return View(devotional);
        }

        // POST: Devotional/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DevotionalId,DevotionalPost,Rating,PostDate,CreatedById")] Devotional devotional)
        {
            if (ModelState.IsValid)
            {
                db.Entry(devotional).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.CreatedById = new SelectList(db.ApplicationUsers, "Id", "FirstName", devotional.CreatedById);
            return View(devotional);
        }

        // GET: Devotional/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Devotional devotional = db.Devotionals.Find(id);
            if (devotional == null)
            {
                return HttpNotFound();
            }
            return View(devotional);
        }

        // POST: Devotional/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Devotional devotional = db.Devotionals.Find(id);
            db.Devotionals.Remove(devotional);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult ThankYou()
        {
            
            return View();
        }
    }
}

GitLoveApp/Views/Devotional/Create.cshtml
@model GitLoveApp.Models.Devotional

@{
    ViewBag.Title = "Post New Devotional";
}
<br />
<h3 style="text-align:center">Create new devotional</h3>
<br />
<br />
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div style="text-align:center">
                @Html.TextAreaFor(model => model.DevotionalPost, 10, 40, null)
                @Html.ValidationMessageFor(model => model.DevotionalPost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div style="text-align:center">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@*<h4 style="text-align:center">@Html.ActionLink("View your list of devotionals", "Index")</h4>*@
<br />
<br />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GitLoveApp/Views/Devotional/Delete.cshtml
@model GitLoveApp.Models.Devotional

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Devotional</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedByUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedByUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DevotionalPost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DevotionalPost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GitLoveApp/Views/Devotional/Details.cshtml
@model GitLoveApp.Models.Devotional

@{
    ViewBag.Title = "Details";
}


<div>
    <h4>Devotional</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedByUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedByUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DevotionalPost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DevotionalPost)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DevotionalId }) |
    @Html.ActionLink("Back to Home", "Index", "Home")
    @Html.ActionLink("Create new devotional", "Create")

</p>

GitLoveApp/Views/Devotional/Edit.cshtml
@model GitLoveApp.Models.Devotional

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Devotional</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DevotionalId)

        <div class="form-group">
            @Html.LabelFor(model => model.DevotionalPost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DevotionalPost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DevotionalPost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedById, "CreatedById", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CreatedById", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CreatedById, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GitLoveApp/Views/Devotional/Index.cshtml
@model IEnumerable<GitLoveApp.Models.Devotional>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreatedByUser.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DevotionalPost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedByUser.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DevotionalPost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DevotionalId }) |
            @Html.ActionLink("Details", "Details", new { id=item.DevotionalId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.DevotionalId })
        </td>
    </tr>
}

</table>

GitLoveApp/Views/Devotional/ThankYou.cshtml
@{
    ViewBag.Title = "ThankYou";
}
<br />
<br />
<h2 class="lead text-center">Thank you for participating.</h2>
<p class="lead text-center">Please log in often to submit all your devotionals.</p>
<br />
<br />
<h4 style="text-align:center">@Html.ActionLink("Post a new devotional", "Create", "Devotional")</h4>
<br />
<br />
<h4 style="text-align:center">@Html.ActionLink("Back to Home", "Index", "Home")</h4>
<br />
<br />